### ISSUE TITLE
cf-workers-access: Add Support for Service Tokens and Cf-Access-Jwt-Assertion header

### ISSUE THREAD

**Issue by GregBrimble** [glenstack/glenstack#1]
If the `CF_Authorization` cookie is absent, try authenticating with [the `Cf-Access-Jwt-Assertion` header](https://developers.cloudflare.com/access/setting-up-access/validate-jwt-tokens/#golang-example) and with [Service Tokens](https://developers.cloudflare.com/access/service-auth/service-token/).

**Comment by GregBrimble** [comment]
JWT when authenticating as a user:

```json
{
  "aud": [
    "f8612530c08484786e83e00ff7b549bc3763747beae55ec909cc28a6a56b81d1"
  ],
  "email": "greg@glenstack.com",
  "exp": 1601097661,
  "iat": 1601011261,
  "nbf": 1601011261,
  "iss": "https://glenstack.cloudflareaccess.com",
  "type": "app",
  "identity_nonce": "1qSnxb2g0hURHBuc",
  "sub": "a0f884f7-a64f-45bf-abb4-466bdedeb484",
  "country": "GB"
}
```

JWT when validating as with Service Auth:

```json
{
  "aud": "f8612530c08484786e83e00ff7b549bc3763747beae55ec909cc28a6a56b81d1",
  "exp": 1601098451,
  "iss": "https://glenstack.cloudflareaccess.com",
  "common_name": "09fe267ad20b0775ed49b8574b1a8aa5.access",
  "iat": 1601012051,
  "sub": ""
}
```

For some reason, `nbf` is missing from the Service Auth JWT. In fact, [`nbf` isn't documented](https://developers.cloudflare.com/access/setting-up-access/json-web-token/#payload) on Cloudflare's docs. So let's just remove that handler.

**Comment by GregBrimble** [comment]
[Fixed](https://github.com/glenstack/glenstack/commit/b973968aa179b5f9052437e63c0d74fb38a93789)

**Comment by GregBrimble** [comment]
(I'm ignoring the `Cf-Access-Jwt-Assertion` header at the moment. If there's a valid use-case for adding it, let me know. Else I'll just continue to only support the `CF_Authorization` cookie.)

**Comment by subhendukundu** [comment]
So what if we wanted to do role-based data access? Making sure only the author has the write access, while reviewer has access to a few extend of the data and while the reader just read the data?
