### ISSUE TITLE
(cf-workers-discord-bot) Asynchronous Fetching

### ISSUE THREAD

**Issue by MRVDOG** [glenstack/glenstack#6]
Hi,
I would first like to apologise as this isn't really an issue per-se,

I have been trying to figure out how to get my InteractionHandler to run an async fetch to my API to request some information based on the options sent by the slash command, but it seems to just fail as soon as it gets to that part of the code and it's frustrating me, just wondered if you had an example of how I can do it

Thanks
~Vinny

p.s. here's an example of my code (using CF's TypeScript example as a base)

```
import fetch from 'node-fetch';

const longestHandler: InteractionHandler = async (
    interaction: Interaction
): Promise<InteractionResponse> => {
    let gif;
    const data = interaction.data;
    const options = data && data.options;

    console.log('data', data, 'options', options);

    const res = await (
        await fetch(`https://domain.com/api/${
            options && options[0] ? options[0].value : 'gifs'
        }/${
            options && options[1] ? options[1].value : ''
        }`)
    ).json();
    console.log('fetch', res);
    
    if ( Array.isArray(res) ) {
        gif = res[Math.floor(Math.random() * res.length)];
    } else {
        gif =  res;
    }

    console.log('gif', gif);
    
    return {
        type: InteractionResponseType.ChannelMessageWithSource,
        data: {
            content: JSON.stringify(options), // debugging
            embeds: [
                {
                    type: EmbedType.image,
                    title: gif.name,
                    url: gif.link.url,
                    image: gif.link.media,
                }
            ],
        },
    };
};
```

**Comment by MRVDOG** [comment]
never mind, I just built it all from scratch, less dependencies

**Comment by GregBrimble** [comment]
Sorry for the late reply! Definitely should be possible to use `await` in handlers. Here's an example of a handler we're using in the Cloudflare Workers Discord server bot: https://github.com/cloudflare-workers-community/cloudflare-workers-discord-bot/blob/master/src/commands/script.ts#L33-L87.

I'd suggest wrapping your logic in a try/catch to see if it's throwing an error when fetching or JSON parsing the response.
