### ISSUE TITLE
Support for followup messages

### ISSUE THREAD

**Issue by cgeopapa** [glenstack/glenstack#7]
Is it possible as for now to send followup messages? 
For example I want my bot to be able to inform the user it got their request to do something and then when that something is done to send a message again confirming its completion.

**Comment by GregBrimble** [comment]
You'd probably want the process to look like this:

1. Incoming request from the slash command;
1. Queue up work (e.g. adding things to KV which gets processed by cron triggers, or using `event.waitUntil`);
1. Respond to the slash command with a ack message;
1. Perform work
1. Send message with [a Webhook](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks).

Hope that makes sense, but let me know if I can clarify something :)
